repos:
-   repo: https://github.com/python/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.720'
    hooks:
    -   id: mypy
-   repo: https://github.com/PyCQA/bandit
    rev: '1.6.2'
    hooks:
    - id: bandit
      args: ['--exclude', 'bookmarks_collection/tests/*']
