name: Check code
on: push

# Thanks to https://medium.com/@vanflymen/blazing-fast-ci-with-github-actions-poetry-black-and-pytest-9e74299dd4a5
# for this configuration

jobs:
  runBlack:
    name: Run Black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Setup Poetry
        uses: dschep/install-poetry-action@db2e37f48d1b1cd1491c4590338ebc7699adb425
      - name: Cache Poetry virtualenv
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-${{ hashFiles('poetry.lock') }}
      - name: Set Poetry config
        run: |
          poetry config virtualenvs.in-project false
          poetry config virtualenvs.path ~/.virtualenvs
      - name: Install dependencies
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Run black
        run: poetry run black . --check

  runBandit:
    name: Run Bandit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: pip install --user bandit
      - name: Run Bandit
        run: /home/runner/.local/bin/bandit -r .

  runMypy:
    name: Run Mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Setup Poetry
        uses: dschep/install-poetry-action@db2e37f48d1b1cd1491c4590338ebc7699adb425
      - name: Cache Poetry virtualenv
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-${{ hashFiles('poetry.lock') }}
      - name: Set Poetry config
        run: |
          poetry config virtualenvs.in-project false
          poetry config virtualenvs.path ~/.virtualenvs
      - name: Install dependencies
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Run Mypy
        run: poetry run mypy bookmarks_collection
